// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_LeftDock = NULL;
lv_obj_t * ui_topBar = NULL;
lv_obj_t * ui_wifiStatus = NULL;
lv_obj_t * ui_Time = NULL;
lv_obj_t * ui_day = NULL;
lv_obj_t * ui_date = NULL;
lv_obj_t * ui_AppsContainer = NULL;
lv_obj_t * ui_youTube = NULL;
lv_obj_t * ui_ytLogo = NULL;
lv_obj_t * ui_ytLabel = NULL;
lv_obj_t * ui_Discord = NULL;
lv_obj_t * ui_discrdLogo = NULL;
lv_obj_t * ui_discordLabel = NULL;
lv_obj_t * ui_Spotify = NULL;
lv_obj_t * ui_SpotifyLogo = NULL;
lv_obj_t * ui_spotifyLabel = NULL;
lv_obj_t * ui_Terminal = NULL;
lv_obj_t * ui_TerminalLogo = NULL;
lv_obj_t * ui_terminalLabel = NULL;
lv_obj_t * ui_Files = NULL;
lv_obj_t * ui_filesLogo = NULL;
lv_obj_t * ui_filesLabel = NULL;
lv_obj_t * ui_settings = NULL;
lv_obj_t * ui_settingsLogo = NULL;
lv_obj_t * ui_settingsLabel = NULL;
lv_obj_t * ui_Netflix = NULL;
lv_obj_t * ui_netflixLogo = NULL;
lv_obj_t * ui_netflixLabel = NULL;
lv_obj_t * ui_custom1 = NULL;
lv_obj_t * ui_customLogo1 = NULL;
lv_obj_t * ui_customLabel1 = NULL;
lv_obj_t * ui_custom2 = NULL;
lv_obj_t * ui_customLogo2 = NULL;
lv_obj_t * ui_customLabel2 = NULL;
lv_obj_t * ui_custom3 = NULL;
lv_obj_t * ui_customLogo3 = NULL;
lv_obj_t * ui_customLabel3 = NULL;
lv_obj_t * ui_custom4 = NULL;
lv_obj_t * ui_customLogo4 = NULL;
lv_obj_t * ui_customLabel4 = NULL;
lv_obj_t * ui_edgeContainer = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_buttonOverlay = NULL;
lv_obj_t * ui_apps = NULL;
lv_obj_t * ui_edge = NULL;
lv_obj_t * ui_TransparencyOverlay = NULL;
lv_obj_t * ui_overlays = NULL;
lv_obj_t * ui_WiFiDisconnected = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_password = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_refreshList = NULL;
lv_obj_t * ui_wifiList = NULL;
// event funtions
void ui_event_wifiStatus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TransparencyOverlay, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_overlays, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_youTube(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_youTube, 100);
        buttonDown_Animation(ui_youTube, 0);
        openYoutube(e);
    }
}

void ui_event_ytLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonDown_Animation(ui_youTube, 0);
        buttonUp_Animation(ui_youTube, 100);
        openYoutube(e);
    }
}

void ui_event_Discord(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_Discord, 100);
        buttonDown_Animation(ui_Discord, 0);
        openDiscord(e);
    }
}

void ui_event_discrdLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonDown_Animation(ui_Discord, 0);
        buttonUp_Animation(ui_Discord, 100);
        openDiscord(e);
    }
}

void ui_event_Spotify(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_Spotify, 100);
        buttonDown_Animation(ui_Spotify, 0);
        openSpotify(e);
    }
}

void ui_event_SpotifyLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonDown_Animation(ui_Spotify, 0);
        buttonUp_Animation(ui_Spotify, 100);
        openSpotify(e);
    }
}

void ui_event_Terminal(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_Terminal, 100);
        buttonDown_Animation(ui_Terminal, 0);
        openTerminal(e);
    }
}

void ui_event_TerminalLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonDown_Animation(ui_Terminal, 0);
        buttonUp_Animation(ui_Terminal, 100);
        openTerminal(e);
    }
}

void ui_event_Files(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_Files, 100);
        buttonDown_Animation(ui_Files, 0);
        openFiles(e);
    }
}

void ui_event_filesLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonDown_Animation(ui_Files, 0);
        buttonUp_Animation(ui_Files, 100);
        openFiles(e);
    }
}

void ui_event_settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_settings, 100);
        buttonDown_Animation(ui_settings, 0);
        openSettings(e);
    }
}

void ui_event_settingsLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonDown_Animation(ui_settings, 0);
        buttonUp_Animation(ui_settings, 100);
        openSettings(e);
    }
}

void ui_event_Netflix(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_Netflix, 100);
        buttonDown_Animation(ui_Netflix, 0);
        openNetflix(e);
    }
}

void ui_event_netflixLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonDown_Animation(ui_Netflix, 0);
        buttonUp_Animation(ui_Netflix, 100);
        openNetflix(e);
    }
}

void ui_event_custom1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_custom1, 100);
        buttonDown_Animation(ui_custom1, 0);
        openCustom1(e);
    }
}

void ui_event_customLogo1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonDown_Animation(ui_custom1, 0);
        buttonUp_Animation(ui_custom1, 100);
        openCustom1(e);
    }
}

void ui_event_custom2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_custom2, 100);
        buttonDown_Animation(ui_custom2, 0);
        openCustom2(e);
    }
}

void ui_event_customLogo2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonDown_Animation(ui_custom2, 0);
        buttonUp_Animation(ui_custom2, 100);
        openCustom2(e);
    }
}

void ui_event_custom3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_custom3, 100);
        buttonDown_Animation(ui_custom3, 0);
        openCustom3(e);
    }
}

void ui_event_customLogo3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonDown_Animation(ui_custom3, 0);
        buttonUp_Animation(ui_custom3, 100);
        openCustom3(e);
    }
}

void ui_event_custom4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_custom4, 100);
        buttonDown_Animation(ui_custom4, 0);
        openCustom3(e);
    }
}

void ui_event_customLogo4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonDown_Animation(ui_custom4, 0);
        buttonUp_Animation(ui_custom4, 100);
        openCustom3(e);
    }
}

void ui_event_apps(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonDown_Animation(ui_apps, 0);
        buttonUp_Animation(ui_apps, 100);
        buttonPressed_X(e);
    }
}

void ui_event_edge(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonDown_Animation(ui_edge, 0);
        buttonUp_Animation(ui_edge, 100);
        buttonPressed_O(e);
    }
}

void ui_event_TransparencyOverlay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_TransparencyOverlay, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_overlays, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_refreshList(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        refreshWifiList(e);
        refersh_Animation(ui_refreshList, 0);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xE6FFF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Screen1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LeftDock = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_LeftDock, 146);
    lv_obj_set_height(ui_LeftDock, 487);
    lv_obj_set_x(ui_LeftDock, -343);
    lv_obj_set_y(ui_LeftDock, -1);
    lv_obj_set_align(ui_LeftDock, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_LeftDock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LeftDock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LeftDock, lv_color_hex(0x9CE8D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LeftDock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_LeftDock, lv_color_hex(0xE9FFF8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_LeftDock, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_LeftDock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_LeftDock, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_LeftDock, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_topBar = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_topBar);
    lv_obj_set_width(ui_topBar, 840);
    lv_obj_set_height(ui_topBar, 119);
    lv_obj_set_x(ui_topBar, -1);
    lv_obj_set_y(ui_topBar, -196);
    lv_obj_set_align(ui_topBar, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_topBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_topBar, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_topBar, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_topBar, lv_color_hex(0x29705B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_topBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_topBar, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_topBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiStatus = lv_image_create(ui_topBar);
    lv_image_set_src(ui_wifiStatus, &ui_img_wifidisabled1_png);
    lv_obj_set_width(ui_wifiStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiStatus, -337);
    lv_obj_set_y(ui_wifiStatus, 12);
    lv_obj_set_align(ui_wifiStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiStatus, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_wifiStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Time = lv_label_create(ui_topBar);
    lv_obj_set_width(ui_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Time, 330);
    lv_obj_set_y(ui_Time, 41);
    lv_label_set_text(ui_Time, "10:00");
    lv_obj_set_style_text_font(ui_Time, &ui_font_Font2l60, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day = lv_label_create(ui_topBar);
    lv_obj_set_width(ui_day, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day, 640);
    lv_obj_set_y(ui_day, 69);
    lv_label_set_text(ui_day, "Thursday");
    lv_obj_set_style_text_align(ui_day, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_day, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_topBar);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, 640);
    lv_obj_set_y(ui_date, 34);
    lv_label_set_text(ui_date, "19-03-2023");
    lv_obj_set_style_text_align(ui_date, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AppsContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_AppsContainer);
    lv_obj_set_width(ui_AppsContainer, 681);
    lv_obj_set_height(ui_AppsContainer, 315);
    lv_obj_set_x(ui_AppsContainer, 80);
    lv_obj_set_y(ui_AppsContainer, 51);
    lv_obj_set_align(ui_AppsContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_AppsContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_AppsContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_AppsContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_AppsContainer, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_AppsContainer, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_AppsContainer, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_AppsContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_youTube = lv_obj_create(ui_AppsContainer);
    lv_obj_remove_style_all(ui_youTube);
    lv_obj_set_width(ui_youTube, 95);
    lv_obj_set_height(ui_youTube, 95);
    lv_obj_set_x(ui_youTube, -250);
    lv_obj_set_y(ui_youTube, -70);
    lv_obj_set_align(ui_youTube, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_youTube, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_youTube, lv_color_hex(0xFFC2C2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_youTube, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_youTube, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_youTube, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_youTube, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_youTube, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ytLogo = lv_image_create(ui_youTube);
    lv_image_set_src(ui_ytLogo, &ui_img_youtube_png);
    lv_obj_set_width(ui_ytLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ytLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ytLogo, 0);
    lv_obj_set_y(ui_ytLogo, -11);
    lv_obj_set_align(ui_ytLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ytLogo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ytLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ytLabel = lv_label_create(ui_youTube);
    lv_obj_set_width(ui_ytLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ytLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ytLabel, 0);
    lv_obj_set_y(ui_ytLabel, 32);
    lv_obj_set_align(ui_ytLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ytLabel, "You Tube");

    ui_Discord = lv_obj_create(ui_AppsContainer);
    lv_obj_remove_style_all(ui_Discord);
    lv_obj_set_width(ui_Discord, 95);
    lv_obj_set_height(ui_Discord, 95);
    lv_obj_set_x(ui_Discord, -125);
    lv_obj_set_y(ui_Discord, -70);
    lv_obj_set_align(ui_Discord, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Discord, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_Discord, lv_color_hex(0xB1B5EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Discord, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Discord, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Discord, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Discord, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Discord, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_discrdLogo = lv_image_create(ui_Discord);
    lv_image_set_src(ui_discrdLogo, &ui_img_discord_png);
    lv_obj_set_width(ui_discrdLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_discrdLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_discrdLogo, 0);
    lv_obj_set_y(ui_discrdLogo, -11);
    lv_obj_set_align(ui_discrdLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_discrdLogo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_discrdLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_discordLabel = lv_label_create(ui_Discord);
    lv_obj_set_width(ui_discordLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_discordLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_discordLabel, 0);
    lv_obj_set_y(ui_discordLabel, 32);
    lv_obj_set_align(ui_discordLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_discordLabel, "Discord");

    ui_Spotify = lv_obj_create(ui_AppsContainer);
    lv_obj_remove_style_all(ui_Spotify);
    lv_obj_set_width(ui_Spotify, 95);
    lv_obj_set_height(ui_Spotify, 95);
    lv_obj_set_x(ui_Spotify, 0);
    lv_obj_set_y(ui_Spotify, -70);
    lv_obj_set_align(ui_Spotify, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Spotify, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_Spotify, lv_color_hex(0x7DC493), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Spotify, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Spotify, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Spotify, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Spotify, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Spotify, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SpotifyLogo = lv_image_create(ui_Spotify);
    lv_image_set_src(ui_SpotifyLogo, &ui_img_spotify_png);
    lv_obj_set_width(ui_SpotifyLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SpotifyLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SpotifyLogo, 0);
    lv_obj_set_y(ui_SpotifyLogo, -11);
    lv_obj_set_align(ui_SpotifyLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SpotifyLogo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_SpotifyLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_spotifyLabel = lv_label_create(ui_Spotify);
    lv_obj_set_width(ui_spotifyLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_spotifyLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_spotifyLabel, 0);
    lv_obj_set_y(ui_spotifyLabel, 32);
    lv_obj_set_align(ui_spotifyLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_spotifyLabel, "Spotify");

    ui_Terminal = lv_obj_create(ui_AppsContainer);
    lv_obj_remove_style_all(ui_Terminal);
    lv_obj_set_width(ui_Terminal, 95);
    lv_obj_set_height(ui_Terminal, 95);
    lv_obj_set_x(ui_Terminal, 125);
    lv_obj_set_y(ui_Terminal, -70);
    lv_obj_set_align(ui_Terminal, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Terminal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_Terminal, lv_color_hex(0x727070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Terminal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Terminal, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Terminal, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Terminal, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Terminal, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TerminalLogo = lv_image_create(ui_Terminal);
    lv_image_set_src(ui_TerminalLogo, &ui_img_terminal_png);
    lv_obj_set_width(ui_TerminalLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TerminalLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TerminalLogo, 2);
    lv_obj_set_y(ui_TerminalLogo, -9);
    lv_obj_set_align(ui_TerminalLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TerminalLogo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_TerminalLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_terminalLabel = lv_label_create(ui_Terminal);
    lv_obj_set_width(ui_terminalLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_terminalLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_terminalLabel, 0);
    lv_obj_set_y(ui_terminalLabel, 32);
    lv_obj_set_align(ui_terminalLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_terminalLabel, "Terminal");

    ui_Files = lv_obj_create(ui_AppsContainer);
    lv_obj_remove_style_all(ui_Files);
    lv_obj_set_width(ui_Files, 95);
    lv_obj_set_height(ui_Files, 95);
    lv_obj_set_x(ui_Files, 255);
    lv_obj_set_y(ui_Files, -70);
    lv_obj_set_align(ui_Files, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Files, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_Files, lv_color_hex(0xFAD990), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Files, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Files, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Files, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Files, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Files, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_filesLogo = lv_image_create(ui_Files);
    lv_image_set_src(ui_filesLogo, &ui_img_folder_png);
    lv_obj_set_width(ui_filesLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_filesLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_filesLogo, 2);
    lv_obj_set_y(ui_filesLogo, -9);
    lv_obj_set_align(ui_filesLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_filesLogo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_filesLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_filesLabel = lv_label_create(ui_Files);
    lv_obj_set_width(ui_filesLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_filesLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_filesLabel, 0);
    lv_obj_set_y(ui_filesLabel, 32);
    lv_obj_set_align(ui_filesLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_filesLabel, "files");

    ui_settings = lv_obj_create(ui_AppsContainer);
    lv_obj_remove_style_all(ui_settings);
    lv_obj_set_width(ui_settings, 95);
    lv_obj_set_height(ui_settings, 95);
    lv_obj_set_x(ui_settings, -250);
    lv_obj_set_y(ui_settings, 70);
    lv_obj_set_align(ui_settings, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_settings, lv_color_hex(0x828FA2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_settings, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_settings, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_settings, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_settings, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsLogo = lv_image_create(ui_settings);
    lv_image_set_src(ui_settingsLogo, &ui_img_cogwheel_png);
    lv_obj_set_width(ui_settingsLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingsLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settingsLogo, 0);
    lv_obj_set_y(ui_settingsLogo, -11);
    lv_obj_set_align(ui_settingsLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingsLogo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_settingsLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settingsLabel = lv_label_create(ui_settings);
    lv_obj_set_width(ui_settingsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settingsLabel, 0);
    lv_obj_set_y(ui_settingsLabel, 32);
    lv_obj_set_align(ui_settingsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settingsLabel, "Settings");

    ui_Netflix = lv_obj_create(ui_AppsContainer);
    lv_obj_remove_style_all(ui_Netflix);
    lv_obj_set_width(ui_Netflix, 95);
    lv_obj_set_height(ui_Netflix, 95);
    lv_obj_set_x(ui_Netflix, -125);
    lv_obj_set_y(ui_Netflix, 70);
    lv_obj_set_align(ui_Netflix, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Netflix, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_Netflix, lv_color_hex(0xFFC2C2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Netflix, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Netflix, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Netflix, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Netflix, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Netflix, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_netflixLogo = lv_image_create(ui_Netflix);
    lv_image_set_src(ui_netflixLogo, &ui_img_netflix_png);
    lv_obj_set_width(ui_netflixLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_netflixLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_netflixLogo, 0);
    lv_obj_set_y(ui_netflixLogo, -11);
    lv_obj_set_align(ui_netflixLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_netflixLogo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_netflixLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_netflixLabel = lv_label_create(ui_Netflix);
    lv_obj_set_width(ui_netflixLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_netflixLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_netflixLabel, 0);
    lv_obj_set_y(ui_netflixLabel, 32);
    lv_obj_set_align(ui_netflixLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_netflixLabel, "Netflix");

    ui_custom1 = lv_obj_create(ui_AppsContainer);
    lv_obj_remove_style_all(ui_custom1);
    lv_obj_set_width(ui_custom1, 95);
    lv_obj_set_height(ui_custom1, 95);
    lv_obj_set_x(ui_custom1, 0);
    lv_obj_set_y(ui_custom1, 70);
    lv_obj_set_align(ui_custom1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_custom1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_custom1, lv_color_hex(0x727070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_custom1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_custom1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_custom1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_custom1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_custom1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_customLogo1 = lv_image_create(ui_custom1);
    lv_image_set_src(ui_customLogo1, &ui_img_custom_png);
    lv_obj_set_width(ui_customLogo1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_customLogo1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_customLogo1, 0);
    lv_obj_set_y(ui_customLogo1, -11);
    lv_obj_set_align(ui_customLogo1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_customLogo1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_customLogo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_customLabel1 = lv_label_create(ui_custom1);
    lv_obj_set_width(ui_customLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_customLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_customLabel1, 0);
    lv_obj_set_y(ui_customLabel1, 32);
    lv_obj_set_align(ui_customLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_customLabel1, "Custom-1");

    ui_custom2 = lv_obj_create(ui_AppsContainer);
    lv_obj_remove_style_all(ui_custom2);
    lv_obj_set_width(ui_custom2, 95);
    lv_obj_set_height(ui_custom2, 95);
    lv_obj_set_x(ui_custom2, 125);
    lv_obj_set_y(ui_custom2, 70);
    lv_obj_set_align(ui_custom2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_custom2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_custom2, lv_color_hex(0x727070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_custom2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_custom2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_custom2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_custom2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_custom2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_customLogo2 = lv_image_create(ui_custom2);
    lv_image_set_src(ui_customLogo2, &ui_img_custom_png);
    lv_obj_set_width(ui_customLogo2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_customLogo2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_customLogo2, 0);
    lv_obj_set_y(ui_customLogo2, -11);
    lv_obj_set_align(ui_customLogo2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_customLogo2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_customLogo2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_customLabel2 = lv_label_create(ui_custom2);
    lv_obj_set_width(ui_customLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_customLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_customLabel2, 0);
    lv_obj_set_y(ui_customLabel2, 32);
    lv_obj_set_align(ui_customLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_customLabel2, "Custom-2");

    ui_custom3 = lv_obj_create(ui_AppsContainer);
    lv_obj_remove_style_all(ui_custom3);
    lv_obj_set_width(ui_custom3, 95);
    lv_obj_set_height(ui_custom3, 95);
    lv_obj_set_x(ui_custom3, 255);
    lv_obj_set_y(ui_custom3, 70);
    lv_obj_set_align(ui_custom3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_custom3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_custom3, lv_color_hex(0x727070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_custom3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_custom3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_custom3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_custom3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_custom3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_customLogo3 = lv_image_create(ui_custom3);
    lv_image_set_src(ui_customLogo3, &ui_img_custom_png);
    lv_obj_set_width(ui_customLogo3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_customLogo3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_customLogo3, 0);
    lv_obj_set_y(ui_customLogo3, -11);
    lv_obj_set_align(ui_customLogo3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_customLogo3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_customLogo3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_customLabel3 = lv_label_create(ui_custom3);
    lv_obj_set_width(ui_customLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_customLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_customLabel3, 0);
    lv_obj_set_y(ui_customLabel3, 32);
    lv_obj_set_align(ui_customLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_customLabel3, "Custom-3");

    ui_custom4 = lv_obj_create(ui_AppsContainer);
    lv_obj_remove_style_all(ui_custom4);
    lv_obj_set_width(ui_custom4, 95);
    lv_obj_set_height(ui_custom4, 95);
    lv_obj_set_x(ui_custom4, 255);
    lv_obj_set_y(ui_custom4, 70);
    lv_obj_set_align(ui_custom4, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_custom4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_custom4, lv_color_hex(0x727070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_custom4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_custom4, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_custom4, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_custom4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_custom4, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_customLogo4 = lv_image_create(ui_custom4);
    lv_image_set_src(ui_customLogo4, &ui_img_custom_png);
    lv_obj_set_width(ui_customLogo4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_customLogo4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_customLogo4, 0);
    lv_obj_set_y(ui_customLogo4, -11);
    lv_obj_set_align(ui_customLogo4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_customLogo4, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_customLogo4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_customLabel4 = lv_label_create(ui_custom4);
    lv_obj_set_width(ui_customLabel4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_customLabel4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_customLabel4, 0);
    lv_obj_set_y(ui_customLabel4, 32);
    lv_obj_set_align(ui_customLabel4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_customLabel4, "Custom-3");

    ui_edgeContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_edgeContainer);
    lv_obj_set_width(ui_edgeContainer, 681);
    lv_obj_set_height(ui_edgeContainer, 315);
    lv_obj_set_x(ui_edgeContainer, 80);
    lv_obj_set_y(ui_edgeContainer, 51);
    lv_obj_set_align(ui_edgeContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_edgeContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_edgeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_edgeContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_edgeContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_edgeContainer, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_edgeContainer, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_edgeContainer, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_edgeContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_edgeContainer);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -16);
    lv_obj_set_y(ui_Label3, -15);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Work in Progress");

    ui_buttonOverlay = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_buttonOverlay);
    lv_obj_set_width(ui_buttonOverlay, 154);
    lv_obj_set_height(ui_buttonOverlay, 154);
    lv_obj_set_x(ui_buttonOverlay, -331);
    lv_obj_set_y(ui_buttonOverlay, -28);
    lv_obj_set_align(ui_buttonOverlay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonOverlay, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_buttonOverlay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonOverlay, lv_color_hex(0x9CE8D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonOverlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_buttonOverlay, lv_color_hex(0xE9FFF8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_buttonOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_buttonOverlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_buttonOverlay, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_buttonOverlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_buttonOverlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_buttonOverlay, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_buttonOverlay, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonOverlay, -17, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonOverlay, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_buttonOverlay, lv_color_hex(0xE6FFF6), LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonOverlay, 255, LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    ui_apps = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_apps, 94);
    lv_obj_set_height(ui_apps, 94);
    lv_obj_set_x(ui_apps, -335);
    lv_obj_set_y(ui_apps, -24);
    lv_obj_set_align(ui_apps, LV_ALIGN_CENTER);
    lv_label_set_text(ui_apps, "X");
    lv_obj_add_flag(ui_apps, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_apps, lv_color_hex(0x0A98F1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_apps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_apps, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_apps, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_apps, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_apps, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_apps, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_apps, lv_color_hex(0x47F6BF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_apps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_apps, lv_color_hex(0xBDFCE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_apps, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_apps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_apps, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_apps, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_apps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_apps, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_apps, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_apps, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_apps, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_apps, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_apps, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_apps, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_apps, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_edge = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_edge, 94);
    lv_obj_set_height(ui_edge, 94);
    lv_obj_set_x(ui_edge, -335);
    lv_obj_set_y(ui_edge, 125);
    lv_obj_set_align(ui_edge, LV_ALIGN_CENTER);
    lv_label_set_text(ui_edge, "O");
    lv_obj_add_flag(ui_edge, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_edge, lv_color_hex(0x0A98F1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_edge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_edge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_edge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_edge, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_edge, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_edge, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_edge, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_edge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_edge, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_edge, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_edge, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_edge, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_edge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_edge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_edge, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_edge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TransparencyOverlay = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_TransparencyOverlay, 832);
    lv_obj_set_height(ui_TransparencyOverlay, 481);
    lv_obj_set_x(ui_TransparencyOverlay, 0);
    lv_obj_set_y(ui_TransparencyOverlay, -1);
    lv_obj_set_align(ui_TransparencyOverlay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TransparencyOverlay, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_TransparencyOverlay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TransparencyOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TransparencyOverlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TransparencyOverlay, 190, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_TransparencyOverlay, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_overlays = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_overlays);
    lv_obj_set_width(ui_overlays, 641);
    lv_obj_set_height(ui_overlays, 409);
    lv_obj_set_align(ui_overlays, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_overlays, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_overlays, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_overlays, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_overlays, lv_color_hex(0xA7E9D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_overlays, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_overlays, lv_color_hex(0xDFE6E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_overlays, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_overlays, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_overlays, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WiFiDisconnected = lv_obj_create(ui_overlays);
    lv_obj_remove_style_all(ui_WiFiDisconnected);
    lv_obj_set_width(ui_WiFiDisconnected, 620);
    lv_obj_set_height(ui_WiFiDisconnected, 398);
    lv_obj_set_x(ui_WiFiDisconnected, 0);
    lv_obj_set_y(ui_WiFiDisconnected, -1);
    lv_obj_set_align(ui_WiFiDisconnected, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WiFiDisconnected, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_WiFiDisconnected);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -105);
    lv_obj_set_y(ui_Label1, -172);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Connect to a Wi-Fi network");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Label1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_Label1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Label1, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Label1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Label1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Label1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Label1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Label1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_password = lv_textarea_create(ui_WiFiDisconnected);
    lv_obj_set_width(ui_password, 300);
    lv_obj_set_height(ui_password, 50);
    lv_obj_set_x(ui_password, -108);
    lv_obj_set_y(ui_password, -68);
    lv_obj_set_align(ui_password, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_password, "password");
    lv_textarea_set_password_mode(ui_password, true);
    lv_obj_set_style_text_font(ui_password, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_WiFiDisconnected);
    lv_obj_set_width(ui_Keyboard1, 596);
    lv_obj_set_height(ui_Keyboard1, 229);
    lv_obj_set_x(ui_Keyboard1, 4);
    lv_obj_set_y(ui_Keyboard1, 75);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Keyboard1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_refreshList = lv_image_create(ui_WiFiDisconnected);
    lv_image_set_src(ui_refreshList, &ui_img_refresh_png);
    lv_obj_set_width(ui_refreshList, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_refreshList, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_refreshList, 66);
    lv_obj_set_y(ui_refreshList, -126);
    lv_obj_set_align(ui_refreshList, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_refreshList, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_refreshList, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiList = lv_dropdown_create(ui_WiFiDisconnected);
    lv_dropdown_set_options(ui_wifiList, "Select Network");
    lv_obj_set_width(ui_wifiList, 300);
    lv_obj_set_height(ui_wifiList, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiList, -108);
    lv_obj_set_y(ui_wifiList, -124);
    lv_obj_set_align(ui_wifiList, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiList, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_wifiList, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_wifiStatus, ui_event_wifiStatus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ytLogo, ui_event_ytLogo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_youTube, ui_event_youTube, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_discrdLogo, ui_event_discrdLogo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Discord, ui_event_Discord, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SpotifyLogo, ui_event_SpotifyLogo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Spotify, ui_event_Spotify, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TerminalLogo, ui_event_TerminalLogo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Terminal, ui_event_Terminal, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_filesLogo, ui_event_filesLogo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Files, ui_event_Files, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingsLogo, ui_event_settingsLogo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settings, ui_event_settings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_netflixLogo, ui_event_netflixLogo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Netflix, ui_event_Netflix, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_customLogo1, ui_event_customLogo1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_custom1, ui_event_custom1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_customLogo2, ui_event_customLogo2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_custom2, ui_event_custom2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_customLogo3, ui_event_customLogo3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_custom3, ui_event_custom3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_customLogo4, ui_event_customLogo4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_custom4, ui_event_custom4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_apps, ui_event_apps, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_edge, ui_event_edge, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TransparencyOverlay, ui_event_TransparencyOverlay, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_Keyboard1, ui_password);
    lv_obj_add_event_cb(ui_refreshList, ui_event_refreshList, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_LeftDock = NULL;
    ui_topBar = NULL;
    ui_wifiStatus = NULL;
    ui_Time = NULL;
    ui_day = NULL;
    ui_date = NULL;
    ui_AppsContainer = NULL;
    ui_youTube = NULL;
    ui_ytLogo = NULL;
    ui_ytLabel = NULL;
    ui_Discord = NULL;
    ui_discrdLogo = NULL;
    ui_discordLabel = NULL;
    ui_Spotify = NULL;
    ui_SpotifyLogo = NULL;
    ui_spotifyLabel = NULL;
    ui_Terminal = NULL;
    ui_TerminalLogo = NULL;
    ui_terminalLabel = NULL;
    ui_Files = NULL;
    ui_filesLogo = NULL;
    ui_filesLabel = NULL;
    ui_settings = NULL;
    ui_settingsLogo = NULL;
    ui_settingsLabel = NULL;
    ui_Netflix = NULL;
    ui_netflixLogo = NULL;
    ui_netflixLabel = NULL;
    ui_custom1 = NULL;
    ui_customLogo1 = NULL;
    ui_customLabel1 = NULL;
    ui_custom2 = NULL;
    ui_customLogo2 = NULL;
    ui_customLabel2 = NULL;
    ui_custom3 = NULL;
    ui_customLogo3 = NULL;
    ui_customLabel3 = NULL;
    ui_custom4 = NULL;
    ui_customLogo4 = NULL;
    ui_customLabel4 = NULL;
    ui_edgeContainer = NULL;
    ui_Label3 = NULL;
    ui_buttonOverlay = NULL;
    ui_apps = NULL;
    ui_edge = NULL;
    ui_TransparencyOverlay = NULL;
    ui_overlays = NULL;
    ui_WiFiDisconnected = NULL;
    ui_Label1 = NULL;
    ui_password = NULL;
    ui_Keyboard1 = NULL;
    ui_refreshList = NULL;
    ui_wifiList = NULL;

}
