// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_LeftDock = NULL;
lv_obj_t * ui_topBar = NULL;
lv_obj_t * ui_wifiStatus = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_day = NULL;
lv_obj_t * ui_date = NULL;
lv_obj_t * ui_appsContainer = NULL;
lv_obj_t * ui_youTube = NULL;
lv_obj_t * ui_ytLogo = NULL;
lv_obj_t * ui_ytLabel = NULL;
lv_obj_t * ui_Discord = NULL;
lv_obj_t * ui_discordLogo = NULL;
lv_obj_t * ui_discordLabel = NULL;
lv_obj_t * ui_spotify = NULL;
lv_obj_t * ui_spotifyLogo = NULL;
lv_obj_t * ui_spotifyLabel = NULL;
lv_obj_t * ui_terminal = NULL;
lv_obj_t * ui_terminalLogo = NULL;
lv_obj_t * ui_terminalLabel = NULL;
lv_obj_t * ui_Files = NULL;
lv_obj_t * ui_filesLogo = NULL;
lv_obj_t * ui_filesLabel = NULL;
lv_obj_t * ui_settings = NULL;
lv_obj_t * ui_settingsLogo = NULL;
lv_obj_t * ui_settingsLabel = NULL;
lv_obj_t * ui_netflix = NULL;
lv_obj_t * ui_netflixLogo = NULL;
lv_obj_t * ui_netflixLabel = NULL;
lv_obj_t * ui_custom1 = NULL;
lv_obj_t * ui_customLogo1 = NULL;
lv_obj_t * ui_customLabel1 = NULL;
lv_obj_t * ui_custom2 = NULL;
lv_obj_t * ui_customLogo2 = NULL;
lv_obj_t * ui_customLabel2 = NULL;
lv_obj_t * ui_custom3 = NULL;
lv_obj_t * ui_customLogo3 = NULL;
lv_obj_t * ui_customLabel3 = NULL;
lv_obj_t * ui_edgeContainer = NULL;
lv_obj_t * ui_temp = NULL;
lv_obj_t * ui_buttonOverlay = NULL;
lv_obj_t * ui_apps = NULL;
lv_obj_t * ui_edge = NULL;
lv_obj_t * ui_transparencyOverlay = NULL;
lv_obj_t * ui_overlays = NULL;
lv_obj_t * ui_wifiConnect = NULL;
lv_obj_t * ui_wifiLabel = NULL;
lv_obj_t * ui_refeshWifi = NULL;
lv_obj_t * ui_password = NULL;
lv_obj_t * ui_passwordDisabled = NULL;
lv_obj_t * ui_keyboard = NULL;
lv_obj_t * ui_wifiList = NULL;
lv_obj_t * ui_wifiRefresh = NULL;
lv_obj_t * ui_scan = NULL;
lv_obj_t * ui_refresh = NULL;
// event funtions
void ui_event_wifiStatus(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_transparencyOverlay, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_overlays, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_youTube(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_youTube, 100);
        buttonDown_Animation(ui_youTube, 0);
        openYoutube(e);
    }
}

void ui_event_ytLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_youTube, 100);
        buttonDown_Animation(ui_youTube, 0);
        openYoutube(e);
    }
}

void ui_event_Discord(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_Discord, 100);
        buttonDown_Animation(ui_Discord, 0);
        openDiscord(e);
    }
}

void ui_event_discordLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_Discord, 100);
        buttonDown_Animation(ui_Discord, 0);
        openDiscord(e);
    }
}

void ui_event_spotify(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_spotify, 100);
        buttonDown_Animation(ui_spotify, 0);
        openSpotify(e);
    }
}

void ui_event_spotifyLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_spotify, 100);
        buttonDown_Animation(ui_spotify, 0);
        openSpotify(e);
    }
}

void ui_event_terminal(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_terminal, 100);
        buttonDown_Animation(ui_terminal, 0);
        openTerminal(e);
    }
}

void ui_event_terminalLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_terminal, 100);
        buttonDown_Animation(ui_terminal, 0);
        openTerminal(e);
    }
}

void ui_event_Files(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_Files, 100);
        buttonDown_Animation(ui_Files, 0);
        openFiles(e);
    }
}

void ui_event_filesLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_Files, 100);
        buttonDown_Animation(ui_Files, 0);
        openFiles(e);
    }
}

void ui_event_settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_settings, 100);
        buttonDown_Animation(ui_settings, 0);
        openSettings(e);
    }
}

void ui_event_settingsLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_settings, 100);
        buttonDown_Animation(ui_settings, 0);
        openSettings(e);
    }
}

void ui_event_netflix(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_netflix, 100);
        buttonDown_Animation(ui_netflix, 0);
        openNetflix(e);
    }
}

void ui_event_netflixLogo(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_netflix, 100);
        buttonDown_Animation(ui_netflix, 0);
        openNetflix(e);
    }
}

void ui_event_custom1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_custom1, 100);
        buttonDown_Animation(ui_custom1, 0);
        openCustom1(e);
    }
}

void ui_event_customLogo1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_custom1, 100);
        buttonDown_Animation(ui_custom1, 0);
        openCustom1(e);
    }
}

void ui_event_custom2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_custom2, 100);
        buttonDown_Animation(ui_custom2, 0);
        openCustom2(e);
    }
}

void ui_event_customLogo2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_custom2, 100);
        buttonDown_Animation(ui_custom2, 0);
        openCustom2(e);
    }
}

void ui_event_custom3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_custom3, 100);
        buttonDown_Animation(ui_custom3, 0);
        openCustom2(e);
    }
}

void ui_event_customLogo3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_custom3, 100);
        buttonDown_Animation(ui_custom3, 0);
        openCustom3(e);
    }
}

void ui_event_apps(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonUp_Animation(ui_apps, 0);
        buttonDown_Animation(ui_apps, 100);
        buttonPressed_X(e);
    }
}

void ui_event_edge(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        buttonDown_Animation(ui_edge, 0);
        buttonUp_Animation(ui_edge, 100);
        buttonPressed_O(e);
    }
}

void ui_event_transparencyOverlay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_transparencyOverlay, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_overlays, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_refeshWifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        refreshWifiList(e);
        _ui_flag_modify(ui_wifiConnect, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_wifiRefresh, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0xE6FFF6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LeftDock = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_LeftDock);
    lv_obj_set_width(ui_LeftDock, 146);
    lv_obj_set_height(ui_LeftDock, 487);
    lv_obj_set_x(ui_LeftDock, -343);
    lv_obj_set_y(ui_LeftDock, -1);
    lv_obj_set_align(ui_LeftDock, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_LeftDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LeftDock, lv_color_hex(0x9CE8D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LeftDock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_LeftDock, lv_color_hex(0xE9FFF8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_LeftDock, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_LeftDock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_LeftDock, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_topBar = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_topBar);
    lv_obj_set_width(ui_topBar, 840);
    lv_obj_set_height(ui_topBar, 119);
    lv_obj_set_x(ui_topBar, 0);
    lv_obj_set_y(ui_topBar, -188);
    lv_obj_set_align(ui_topBar, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_topBar, LV_OBJ_FLAG_FLEX_IN_NEW_TRACK);     /// Flags
    lv_obj_remove_flag(ui_topBar, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_topBar, lv_color_hex(0x999999), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_topBar, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_topBar, lv_color_hex(0x29705B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_topBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_topBar, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_topBar, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiStatus = lv_image_create(ui_topBar);
    lv_image_set_src(ui_wifiStatus, &ui_img_wifi_png);
    lv_obj_set_width(ui_wifiStatus, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiStatus, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiStatus, -319);
    lv_obj_set_y(ui_wifiStatus, 5);
    lv_obj_set_align(ui_wifiStatus, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiStatus, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_wifiStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_time = lv_label_create(ui_topBar);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "10:00");
    lv_obj_set_style_text_font(ui_time, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_day = lv_label_create(ui_topBar);
    lv_obj_set_width(ui_day, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_day, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_day, 288);
    lv_obj_set_y(ui_day, 17);
    lv_obj_set_align(ui_day, LV_ALIGN_CENTER);
    lv_label_set_text(ui_day, "Thursday");
    lv_obj_set_style_text_font(ui_day, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_topBar);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, 288);
    lv_obj_set_y(ui_date, -17);
    lv_obj_set_align(ui_date, LV_ALIGN_CENTER);
    lv_label_set_text(ui_date, "19-03-2025");
    lv_obj_set_style_text_font(ui_date, &lv_font_montserrat_32, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_appsContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_appsContainer);
    lv_obj_set_width(ui_appsContainer, 681);
    lv_obj_set_height(ui_appsContainer, 315);
    lv_obj_set_x(ui_appsContainer, 80);
    lv_obj_set_y(ui_appsContainer, 55);
    lv_obj_set_align(ui_appsContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_appsContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_appsContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_appsContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_appsContainer, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_appsContainer, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_appsContainer, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_appsContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_youTube = lv_obj_create(ui_appsContainer);
    lv_obj_remove_style_all(ui_youTube);
    lv_obj_set_width(ui_youTube, 95);
    lv_obj_set_height(ui_youTube, 95);
    lv_obj_set_x(ui_youTube, -250);
    lv_obj_set_y(ui_youTube, -70);
    lv_obj_set_align(ui_youTube, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_youTube, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_youTube, lv_color_hex(0xFFC2C2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_youTube, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_youTube, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_youTube, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_youTube, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_youTube, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ytLogo = lv_image_create(ui_youTube);
    lv_image_set_src(ui_ytLogo, &ui_img_youtube_png);
    lv_obj_set_width(ui_ytLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ytLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ytLogo, 0);
    lv_obj_set_y(ui_ytLogo, -11);
    lv_obj_set_align(ui_ytLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ytLogo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_ytLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ytLabel = lv_label_create(ui_youTube);
    lv_obj_set_width(ui_ytLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ytLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ytLabel, 0);
    lv_obj_set_y(ui_ytLabel, 32);
    lv_obj_set_align(ui_ytLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ytLabel, "YouTube");

    ui_Discord = lv_obj_create(ui_appsContainer);
    lv_obj_remove_style_all(ui_Discord);
    lv_obj_set_width(ui_Discord, 95);
    lv_obj_set_height(ui_Discord, 95);
    lv_obj_set_x(ui_Discord, -125);
    lv_obj_set_y(ui_Discord, -70);
    lv_obj_set_align(ui_Discord, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Discord, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_Discord, lv_color_hex(0xB1B5EE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Discord, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Discord, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Discord, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Discord, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Discord, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_discordLogo = lv_image_create(ui_Discord);
    lv_image_set_src(ui_discordLogo, &ui_img_discord_png);
    lv_obj_set_width(ui_discordLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_discordLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_discordLogo, 0);
    lv_obj_set_y(ui_discordLogo, -11);
    lv_obj_set_align(ui_discordLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_discordLogo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_discordLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_discordLabel = lv_label_create(ui_Discord);
    lv_obj_set_width(ui_discordLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_discordLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_discordLabel, 0);
    lv_obj_set_y(ui_discordLabel, 32);
    lv_obj_set_align(ui_discordLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_discordLabel, "Discord");

    ui_spotify = lv_obj_create(ui_appsContainer);
    lv_obj_remove_style_all(ui_spotify);
    lv_obj_set_width(ui_spotify, 95);
    lv_obj_set_height(ui_spotify, 95);
    lv_obj_set_x(ui_spotify, 0);
    lv_obj_set_y(ui_spotify, -70);
    lv_obj_set_align(ui_spotify, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_spotify, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_spotify, lv_color_hex(0x7DC493), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_spotify, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_spotify, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_spotify, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_spotify, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_spotify, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_spotifyLogo = lv_image_create(ui_spotify);
    lv_image_set_src(ui_spotifyLogo, &ui_img_spotify_png);
    lv_obj_set_width(ui_spotifyLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_spotifyLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_spotifyLogo, 0);
    lv_obj_set_y(ui_spotifyLogo, -11);
    lv_obj_set_align(ui_spotifyLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_spotifyLogo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_spotifyLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_spotifyLabel = lv_label_create(ui_spotify);
    lv_obj_set_width(ui_spotifyLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_spotifyLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_spotifyLabel, 0);
    lv_obj_set_y(ui_spotifyLabel, 32);
    lv_obj_set_align(ui_spotifyLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_spotifyLabel, "Spotify");

    ui_terminal = lv_obj_create(ui_appsContainer);
    lv_obj_remove_style_all(ui_terminal);
    lv_obj_set_width(ui_terminal, 95);
    lv_obj_set_height(ui_terminal, 95);
    lv_obj_set_x(ui_terminal, 125);
    lv_obj_set_y(ui_terminal, -70);
    lv_obj_set_align(ui_terminal, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_terminal, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_terminal, lv_color_hex(0x727070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_terminal, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_terminal, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_terminal, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_terminal, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_terminal, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_terminalLogo = lv_image_create(ui_terminal);
    lv_image_set_src(ui_terminalLogo, &ui_img_terminal_png);
    lv_obj_set_width(ui_terminalLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_terminalLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_terminalLogo, 0);
    lv_obj_set_y(ui_terminalLogo, -11);
    lv_obj_set_align(ui_terminalLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_terminalLogo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_terminalLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_terminalLabel = lv_label_create(ui_terminal);
    lv_obj_set_width(ui_terminalLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_terminalLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_terminalLabel, 0);
    lv_obj_set_y(ui_terminalLabel, 32);
    lv_obj_set_align(ui_terminalLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_terminalLabel, "Terminal");

    ui_Files = lv_obj_create(ui_appsContainer);
    lv_obj_remove_style_all(ui_Files);
    lv_obj_set_width(ui_Files, 95);
    lv_obj_set_height(ui_Files, 95);
    lv_obj_set_x(ui_Files, 255);
    lv_obj_set_y(ui_Files, -70);
    lv_obj_set_align(ui_Files, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Files, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_Files, lv_color_hex(0xFAD990), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Files, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Files, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Files, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_Files, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_Files, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_filesLogo = lv_image_create(ui_Files);
    lv_image_set_src(ui_filesLogo, &ui_img_folder_png);
    lv_obj_set_width(ui_filesLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_filesLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_filesLogo, 0);
    lv_obj_set_y(ui_filesLogo, -11);
    lv_obj_set_align(ui_filesLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_filesLogo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_filesLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_filesLabel = lv_label_create(ui_Files);
    lv_obj_set_width(ui_filesLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_filesLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_filesLabel, 0);
    lv_obj_set_y(ui_filesLabel, 32);
    lv_obj_set_align(ui_filesLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_filesLabel, "Files");

    ui_settings = lv_obj_create(ui_appsContainer);
    lv_obj_remove_style_all(ui_settings);
    lv_obj_set_width(ui_settings, 95);
    lv_obj_set_height(ui_settings, 95);
    lv_obj_set_x(ui_settings, -250);
    lv_obj_set_y(ui_settings, 70);
    lv_obj_set_align(ui_settings, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_settings, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_settings, lv_color_hex(0x828FA2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_settings, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_settings, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_settings, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_settings, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_settings, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingsLogo = lv_image_create(ui_settings);
    lv_image_set_src(ui_settingsLogo, &ui_img_cogwheel_png);
    lv_obj_set_width(ui_settingsLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingsLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settingsLogo, 0);
    lv_obj_set_y(ui_settingsLogo, -11);
    lv_obj_set_align(ui_settingsLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingsLogo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_settingsLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settingsLabel = lv_label_create(ui_settings);
    lv_obj_set_width(ui_settingsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_settingsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_settingsLabel, 0);
    lv_obj_set_y(ui_settingsLabel, 32);
    lv_obj_set_align(ui_settingsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_settingsLabel, "Settings");

    ui_netflix = lv_obj_create(ui_appsContainer);
    lv_obj_remove_style_all(ui_netflix);
    lv_obj_set_width(ui_netflix, 95);
    lv_obj_set_height(ui_netflix, 95);
    lv_obj_set_x(ui_netflix, -125);
    lv_obj_set_y(ui_netflix, 70);
    lv_obj_set_align(ui_netflix, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_netflix, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_netflix, lv_color_hex(0xFFC2C2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_netflix, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_netflix, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_netflix, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_netflix, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_netflix, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_netflixLogo = lv_image_create(ui_netflix);
    lv_image_set_src(ui_netflixLogo, &ui_img_netflix_png);
    lv_obj_set_width(ui_netflixLogo, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_netflixLogo, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_netflixLogo, 0);
    lv_obj_set_y(ui_netflixLogo, -11);
    lv_obj_set_align(ui_netflixLogo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_netflixLogo, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_netflixLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_netflixLabel = lv_label_create(ui_netflix);
    lv_obj_set_width(ui_netflixLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_netflixLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_netflixLabel, 0);
    lv_obj_set_y(ui_netflixLabel, 32);
    lv_obj_set_align(ui_netflixLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_netflixLabel, "Netflix");

    ui_custom1 = lv_obj_create(ui_appsContainer);
    lv_obj_remove_style_all(ui_custom1);
    lv_obj_set_width(ui_custom1, 95);
    lv_obj_set_height(ui_custom1, 95);
    lv_obj_set_x(ui_custom1, 0);
    lv_obj_set_y(ui_custom1, 70);
    lv_obj_set_align(ui_custom1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_custom1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_custom1, lv_color_hex(0x727070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_custom1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_custom1, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_custom1, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_custom1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_custom1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_customLogo1 = lv_image_create(ui_custom1);
    lv_image_set_src(ui_customLogo1, &ui_img_settings_png);
    lv_obj_set_width(ui_customLogo1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_customLogo1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_customLogo1, 0);
    lv_obj_set_y(ui_customLogo1, -11);
    lv_obj_set_align(ui_customLogo1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_customLogo1, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_customLogo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_customLabel1 = lv_label_create(ui_custom1);
    lv_obj_set_width(ui_customLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_customLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_customLabel1, 0);
    lv_obj_set_y(ui_customLabel1, 32);
    lv_obj_set_align(ui_customLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_customLabel1, "Custom-1");

    ui_custom2 = lv_obj_create(ui_appsContainer);
    lv_obj_remove_style_all(ui_custom2);
    lv_obj_set_width(ui_custom2, 95);
    lv_obj_set_height(ui_custom2, 95);
    lv_obj_set_x(ui_custom2, 125);
    lv_obj_set_y(ui_custom2, 70);
    lv_obj_set_align(ui_custom2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_custom2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_custom2, lv_color_hex(0x727070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_custom2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_custom2, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_custom2, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_custom2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_custom2, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_customLogo2 = lv_image_create(ui_custom2);
    lv_image_set_src(ui_customLogo2, &ui_img_settings_png);
    lv_obj_set_width(ui_customLogo2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_customLogo2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_customLogo2, 0);
    lv_obj_set_y(ui_customLogo2, -11);
    lv_obj_set_align(ui_customLogo2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_customLogo2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_customLogo2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_customLabel2 = lv_label_create(ui_custom2);
    lv_obj_set_width(ui_customLabel2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_customLabel2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_customLabel2, 0);
    lv_obj_set_y(ui_customLabel2, 32);
    lv_obj_set_align(ui_customLabel2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_customLabel2, "Custom-2");

    ui_custom3 = lv_obj_create(ui_appsContainer);
    lv_obj_remove_style_all(ui_custom3);
    lv_obj_set_width(ui_custom3, 95);
    lv_obj_set_height(ui_custom3, 95);
    lv_obj_set_x(ui_custom3, 255);
    lv_obj_set_y(ui_custom3, 70);
    lv_obj_set_align(ui_custom3, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_custom3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_custom3, lv_color_hex(0x727070), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_custom3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_custom3, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_custom3, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_custom3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_custom3, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_customLogo3 = lv_image_create(ui_custom3);
    lv_image_set_src(ui_customLogo3, &ui_img_settings_png);
    lv_obj_set_width(ui_customLogo3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_customLogo3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_customLogo3, 0);
    lv_obj_set_y(ui_customLogo3, -11);
    lv_obj_set_align(ui_customLogo3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_customLogo3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_customLogo3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_customLabel3 = lv_label_create(ui_custom3);
    lv_obj_set_width(ui_customLabel3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_customLabel3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_customLabel3, 0);
    lv_obj_set_y(ui_customLabel3, 32);
    lv_obj_set_align(ui_customLabel3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_customLabel3, "Custom-3");

    ui_edgeContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_edgeContainer);
    lv_obj_set_width(ui_edgeContainer, 681);
    lv_obj_set_height(ui_edgeContainer, 315);
    lv_obj_set_x(ui_edgeContainer, 80);
    lv_obj_set_y(ui_edgeContainer, 55);
    lv_obj_set_align(ui_edgeContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_edgeContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_edgeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_shadow_color(ui_edgeContainer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_edgeContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_edgeContainer, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_edgeContainer, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_edgeContainer, -1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_edgeContainer, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_temp = lv_label_create(ui_edgeContainer);
    lv_obj_set_width(ui_temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_temp, -16);
    lv_obj_set_y(ui_temp, -15);
    lv_obj_set_align(ui_temp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_temp, "Work in Progress");

    ui_buttonOverlay = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_buttonOverlay);
    lv_obj_set_width(ui_buttonOverlay, 154);
    lv_obj_set_height(ui_buttonOverlay, 154);
    lv_obj_set_x(ui_buttonOverlay, -331);
    lv_obj_set_y(ui_buttonOverlay, -24);
    lv_obj_set_align(ui_buttonOverlay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_buttonOverlay, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_remove_flag(ui_buttonOverlay, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_buttonOverlay, lv_color_hex(0x9CE8D1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_buttonOverlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_buttonOverlay, lv_color_hex(0xE9FFF8), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_buttonOverlay, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_buttonOverlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_buttonOverlay, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_buttonOverlay, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_buttonOverlay, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_buttonOverlay, -17, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_buttonOverlay, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_apps = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_apps, 94);
    lv_obj_set_height(ui_apps, 94);
    lv_obj_set_x(ui_apps, -335);
    lv_obj_set_y(ui_apps, -24);
    lv_obj_set_align(ui_apps, LV_ALIGN_CENTER);
    lv_label_set_text(ui_apps, "X");
    lv_obj_add_flag(ui_apps, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_apps, lv_color_hex(0x0A98F1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_apps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_apps, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_apps, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_apps, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_apps, lv_color_hex(0x47F6BF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_apps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_apps, lv_color_hex(0xBDFCE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_apps, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_apps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_apps, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_apps, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_apps, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_apps, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_apps, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_apps, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_apps, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_apps, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_apps, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_apps, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_apps, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_edge = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_edge, 94);
    lv_obj_set_height(ui_edge, 94);
    lv_obj_set_x(ui_edge, -335);
    lv_obj_set_y(ui_edge, 129);
    lv_obj_set_align(ui_edge, LV_ALIGN_CENTER);
    lv_label_set_text(ui_edge, "O");
    lv_obj_add_flag(ui_edge, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_color(ui_edge, lv_color_hex(0x0A98F1), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_edge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_edge, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_edge, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_edge, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_edge, lv_color_hex(0xBDFCE7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_edge, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_edge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_edge, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_edge, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_edge, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_edge, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_edge, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_x(ui_edge, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_offset_y(ui_edge, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_edge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_edge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_edge, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_edge, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_transparencyOverlay = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_transparencyOverlay);
    lv_obj_set_width(ui_transparencyOverlay, 832);
    lv_obj_set_height(ui_transparencyOverlay, 480);
    lv_obj_set_align(ui_transparencyOverlay, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_transparencyOverlay, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_transparencyOverlay, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_transparencyOverlay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_transparencyOverlay, 190, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_overlays = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_overlays);
    lv_obj_set_width(ui_overlays, 641);
    lv_obj_set_height(ui_overlays, 409);
    lv_obj_set_align(ui_overlays, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_overlays, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_overlays, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_overlays, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_overlays, lv_color_hex(0xA7E9D5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_overlays, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_overlays, lv_color_hex(0xDFE6E4), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_overlays, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_overlays, 150, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_overlays, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiConnect = lv_obj_create(ui_overlays);
    lv_obj_remove_style_all(ui_wifiConnect);
    lv_obj_set_width(ui_wifiConnect, 620);
    lv_obj_set_height(ui_wifiConnect, 398);
    lv_obj_set_align(ui_wifiConnect, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiConnect, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_remove_flag(ui_wifiConnect, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wifiLabel = lv_label_create(ui_wifiConnect);
    lv_obj_set_width(ui_wifiLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wifiLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiLabel, -105);
    lv_obj_set_y(ui_wifiLabel, -172);
    lv_obj_set_align(ui_wifiLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wifiLabel, "Connect to a Wi-Fi network");
    lv_obj_set_style_text_font(ui_wifiLabel, &lv_font_montserrat_22, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_wifiLabel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_wifiLabel, lv_color_hex(0xB4EAD5), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_wifiLabel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_wifiLabel, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_wifiLabel, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_wifiLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_wifiLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_wifiLabel, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_wifiLabel, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_refeshWifi = lv_image_create(ui_wifiConnect);
    lv_image_set_src(ui_refeshWifi, &ui_img_refresh_png);
    lv_obj_set_width(ui_refeshWifi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_refeshWifi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_refeshWifi, 66);
    lv_obj_set_y(ui_refeshWifi, -126);
    lv_obj_set_align(ui_refeshWifi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_refeshWifi, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_remove_flag(ui_refeshWifi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_password = lv_textarea_create(ui_wifiConnect);
    lv_obj_set_width(ui_password, 300);
    lv_obj_set_height(ui_password, 50);
    lv_obj_set_x(ui_password, -108);
    lv_obj_set_y(ui_password, -68);
    lv_obj_set_align(ui_password, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_password, "password");
    lv_textarea_set_password_mode(ui_password, true);
    lv_obj_set_style_text_font(ui_password, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_passwordDisabled = lv_textarea_create(ui_wifiConnect);
    lv_obj_set_width(ui_passwordDisabled, 300);
    lv_obj_set_height(ui_passwordDisabled, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_passwordDisabled, -108);
    lv_obj_set_y(ui_passwordDisabled, -68);
    lv_obj_set_align(ui_passwordDisabled, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_passwordDisabled, "open security");
    lv_textarea_set_one_line(ui_passwordDisabled, true);
    lv_textarea_set_password_mode(ui_passwordDisabled, true);
    lv_obj_add_state(ui_passwordDisabled, LV_STATE_DISABLED);       /// States
    lv_obj_add_flag(ui_passwordDisabled, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_font(ui_passwordDisabled, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_keyboard = lv_keyboard_create(ui_wifiConnect);
    lv_obj_set_width(ui_keyboard, 596);
    lv_obj_set_height(ui_keyboard, 229);
    lv_obj_set_x(ui_keyboard, 4);
    lv_obj_set_y(ui_keyboard, 75);
    lv_obj_set_align(ui_keyboard, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_keyboard, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiList = lv_dropdown_create(ui_wifiConnect);
    lv_dropdown_set_options(ui_wifiList, "Select Network");
    lv_obj_set_width(ui_wifiList, 300);
    lv_obj_set_height(ui_wifiList, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wifiList, -108);
    lv_obj_set_y(ui_wifiList, -124);
    lv_obj_set_align(ui_wifiList, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_wifiList, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_wifiList, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_wifiList, &lv_font_montserrat_20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_wifiList), &lv_font_montserrat_20,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_wifiRefresh = lv_obj_create(ui_overlays);
    lv_obj_remove_style_all(ui_wifiRefresh);
    lv_obj_set_width(ui_wifiRefresh, 620);
    lv_obj_set_height(ui_wifiRefresh, 398);
    lv_obj_set_align(ui_wifiRefresh, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_wifiRefresh, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_scan = lv_label_create(ui_wifiRefresh);
    lv_obj_set_width(ui_scan, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_scan, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_scan, 4);
    lv_obj_set_y(ui_scan, 45);
    lv_obj_set_align(ui_scan, LV_ALIGN_CENTER);
    lv_label_set_text(ui_scan, "Scanning for Network");
    lv_obj_set_style_text_font(ui_scan, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_scan, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_scan, lv_color_hex(0xDEE6E6), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_scan, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_scan, 50, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_scan, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_scan, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_scan, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_scan, 3, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_scan, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_refresh = lv_spinner_create(ui_wifiRefresh);
    //lv_spinner_set_anim_params(ui_refresh, 1000, 90);
    lv_obj_set_width(ui_refresh, 80);
    lv_obj_set_height(ui_refresh, 80);
    lv_obj_set_x(ui_refresh, 0);
    lv_obj_set_y(ui_refresh, -19);
    lv_obj_set_align(ui_refresh, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_refresh, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_arc_color(ui_refresh, lv_color_hex(0x47F6BF), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_refresh, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_wifiStatus, ui_event_wifiStatus, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ytLogo, ui_event_ytLogo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_youTube, ui_event_youTube, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_discordLogo, ui_event_discordLogo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Discord, ui_event_Discord, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_spotifyLogo, ui_event_spotifyLogo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_spotify, ui_event_spotify, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_terminalLogo, ui_event_terminalLogo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_terminal, ui_event_terminal, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_filesLogo, ui_event_filesLogo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Files, ui_event_Files, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingsLogo, ui_event_settingsLogo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settings, ui_event_settings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_netflixLogo, ui_event_netflixLogo, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_netflix, ui_event_netflix, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_customLogo1, ui_event_customLogo1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_custom1, ui_event_custom1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_customLogo2, ui_event_customLogo2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_custom2, ui_event_custom2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_customLogo3, ui_event_customLogo3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_custom3, ui_event_custom3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_apps, ui_event_apps, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_edge, ui_event_edge, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_transparencyOverlay, ui_event_transparencyOverlay, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_refeshWifi, ui_event_refeshWifi, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_keyboard, ui_password);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_LeftDock = NULL;
    ui_topBar = NULL;
    ui_wifiStatus = NULL;
    ui_time = NULL;
    ui_day = NULL;
    ui_date = NULL;
    ui_appsContainer = NULL;
    ui_youTube = NULL;
    ui_ytLogo = NULL;
    ui_ytLabel = NULL;
    ui_Discord = NULL;
    ui_discordLogo = NULL;
    ui_discordLabel = NULL;
    ui_spotify = NULL;
    ui_spotifyLogo = NULL;
    ui_spotifyLabel = NULL;
    ui_terminal = NULL;
    ui_terminalLogo = NULL;
    ui_terminalLabel = NULL;
    ui_Files = NULL;
    ui_filesLogo = NULL;
    ui_filesLabel = NULL;
    ui_settings = NULL;
    ui_settingsLogo = NULL;
    ui_settingsLabel = NULL;
    ui_netflix = NULL;
    ui_netflixLogo = NULL;
    ui_netflixLabel = NULL;
    ui_custom1 = NULL;
    ui_customLogo1 = NULL;
    ui_customLabel1 = NULL;
    ui_custom2 = NULL;
    ui_customLogo2 = NULL;
    ui_customLabel2 = NULL;
    ui_custom3 = NULL;
    ui_customLogo3 = NULL;
    ui_customLabel3 = NULL;
    ui_edgeContainer = NULL;
    ui_temp = NULL;
    ui_buttonOverlay = NULL;
    ui_apps = NULL;
    ui_edge = NULL;
    ui_transparencyOverlay = NULL;
    ui_overlays = NULL;
    ui_wifiConnect = NULL;
    ui_wifiLabel = NULL;
    ui_refeshWifi = NULL;
    ui_password = NULL;
    ui_passwordDisabled = NULL;
    ui_keyboard = NULL;
    ui_wifiList = NULL;
    ui_wifiRefresh = NULL;
    ui_scan = NULL;
    ui_refresh = NULL;

}
