// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_LeftDock;
extern lv_obj_t * ui_topBar;
extern void ui_event_wifiStatus(lv_event_t * e);
extern lv_obj_t * ui_wifiStatus;
extern lv_obj_t * ui_time;
extern lv_obj_t * ui_day;
extern lv_obj_t * ui_date;
extern lv_obj_t * ui_appsContainer;
extern void ui_event_youTube(lv_event_t * e);
extern lv_obj_t * ui_youTube;
extern void ui_event_ytLogo(lv_event_t * e);
extern lv_obj_t * ui_ytLogo;
extern lv_obj_t * ui_ytLabel;
extern void ui_event_Discord(lv_event_t * e);
extern lv_obj_t * ui_Discord;
extern void ui_event_discordLogo(lv_event_t * e);
extern lv_obj_t * ui_discordLogo;
extern lv_obj_t * ui_discordLabel;
extern void ui_event_spotify(lv_event_t * e);
extern lv_obj_t * ui_spotify;
extern void ui_event_spotifyLogo(lv_event_t * e);
extern lv_obj_t * ui_spotifyLogo;
extern lv_obj_t * ui_spotifyLabel;
extern void ui_event_terminal(lv_event_t * e);
extern lv_obj_t * ui_terminal;
extern void ui_event_terminalLogo(lv_event_t * e);
extern lv_obj_t * ui_terminalLogo;
extern lv_obj_t * ui_terminalLabel;
extern void ui_event_Files(lv_event_t * e);
extern lv_obj_t * ui_Files;
extern void ui_event_filesLogo(lv_event_t * e);
extern lv_obj_t * ui_filesLogo;
extern lv_obj_t * ui_filesLabel;
extern void ui_event_settings(lv_event_t * e);
extern lv_obj_t * ui_settings;
extern void ui_event_settingsLogo(lv_event_t * e);
extern lv_obj_t * ui_settingsLogo;
extern lv_obj_t * ui_settingsLabel;
extern void ui_event_netflix(lv_event_t * e);
extern lv_obj_t * ui_netflix;
extern void ui_event_netflixLogo(lv_event_t * e);
extern lv_obj_t * ui_netflixLogo;
extern lv_obj_t * ui_netflixLabel;
extern void ui_event_custom1(lv_event_t * e);
extern lv_obj_t * ui_custom1;
extern void ui_event_customLogo1(lv_event_t * e);
extern lv_obj_t * ui_customLogo1;
extern lv_obj_t * ui_customLabel1;
extern void ui_event_custom2(lv_event_t * e);
extern lv_obj_t * ui_custom2;
extern void ui_event_customLogo2(lv_event_t * e);
extern lv_obj_t * ui_customLogo2;
extern lv_obj_t * ui_customLabel2;
extern void ui_event_custom3(lv_event_t * e);
extern lv_obj_t * ui_custom3;
extern void ui_event_customLogo3(lv_event_t * e);
extern lv_obj_t * ui_customLogo3;
extern lv_obj_t * ui_customLabel3;
extern lv_obj_t * ui_edgeContainer;
extern lv_obj_t * ui_temp;
extern lv_obj_t * ui_buttonOverlay;
extern void ui_event_apps(lv_event_t * e);
extern lv_obj_t * ui_apps;
extern void ui_event_edge(lv_event_t * e);
extern lv_obj_t * ui_edge;
extern void ui_event_transparencyOverlay(lv_event_t * e);
extern lv_obj_t * ui_transparencyOverlay;
extern lv_obj_t * ui_overlays;
extern lv_obj_t * ui_wifiConnect;
extern lv_obj_t * ui_wifiLabel;
extern void ui_event_refeshWifi(lv_event_t * e);
extern lv_obj_t * ui_refeshWifi;
extern lv_obj_t * ui_password;
extern lv_obj_t * ui_passwordDisabled;
extern lv_obj_t * ui_keyboard;
extern void ui_event_wifiList(lv_event_t * e);
extern lv_obj_t * ui_wifiList;
extern lv_obj_t * ui_wifiCredential;
extern void ui_event_connectBtn(lv_event_t * e);
extern lv_obj_t * ui_connectBtn;
extern lv_obj_t * ui_connectBtnLabel;
extern void ui_event_deleteCredential(lv_event_t * e);
extern lv_obj_t * ui_deleteCredential;
extern lv_obj_t * ui_wifiRefresh;
extern lv_obj_t * ui_scan;
extern lv_obj_t * ui_refresh;
extern lv_obj_t * ui_notification;
extern lv_obj_t * ui_notificationLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

