// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * buttonUp_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * buttonDown_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_youtube_png);    // assets/youtube.png
LV_IMG_DECLARE(ui_img_discord_png);    // assets/discord.png
LV_IMG_DECLARE(ui_img_spotify_png);    // assets/spotify.png
LV_IMG_DECLARE(ui_img_terminal_png);    // assets/terminal.png
LV_IMG_DECLARE(ui_img_folder_png);    // assets/folder.png
LV_IMG_DECLARE(ui_img_cogwheel_png);    // assets/cogwheel.png
LV_IMG_DECLARE(ui_img_netflix_png);    // assets/netflix.png
LV_IMG_DECLARE(ui_img_settings_png);    // assets/settings.png
LV_IMG_DECLARE(ui_img_refresh_png);    // assets/refresh.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
