// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void openYoutube(lv_event_t * e);
void openDiscord(lv_event_t * e);
void openSpotify(lv_event_t * e);
void openTerminal(lv_event_t * e);
void openFiles(lv_event_t * e);
void openSettings(lv_event_t * e);
void openNetflix(lv_event_t * e);
void openCustom1(lv_event_t * e);
void openCustom2(lv_event_t * e);
void openCustom3(lv_event_t * e);
void buttonPressed_X(lv_event_t * e);
void buttonPressed_O(lv_event_t * e);
void refreshWifiList(lv_event_t * e);
void updateWifiCredential(lv_event_t * e);
void connectWifi(lv_event_t * e);
void disconnectWifi(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
